apiVersion: apps/v1
kind: Deployment
metadata:
  name: authservice-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: AuthServiceStatic
  template:
    metadata:
      labels:
        app: AuthServiceStatic
    spec:
      containers:
      - name: authservicesrepos
        image: samplecr1.azurecr.io/authservicesrepos:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: dsconfigsn

---
apiVersion: v1
kind: Service
metadata:
  name: authservice
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: AuthServiceStatic
